name: flutter_blue_plus_example
description: Demonstrates how to use the flutter_blue_plus plugin.
version: 1.0.0+1 # version

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.8
  shared_preferences: ^2.0.6

  # Uncomment the following lines if you are developing both the plugin and the example together.
  # flutter_blue_plus:
  #   path: ../

flutter:
  uses-material-design: true
